// Role names
export const PERMISSION_LEVELS = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  MASTER_DATA_EDITOR: "MASTER_DATA_EDITOR",
  USER: "USER",
};

// All possible permissions
export const ALL_PERMISSIONS = [
  PERMISSION_LEVELS.SUPER_ADMIN,
  PERMISSION_LEVELS.ADMIN,
  PERMISSION_LEVELS.MASTER_DATA_EDITOR,
  PERMISSION_LEVELS.USER,
];
